sonar.projectKey=Lewan_CICD_TaskList_Backend
sonar.projectName=lewan-cicd-tasklist-backend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/server.ts,src/lib/prisma.ts,**/*.config.ts,src/__tests__/**

sonar.exclusions=node_modules/**,dist/**,coverage/**,reports/**,prisma/**

sonar.sourceEncoding=UTF-8
